# Generated by Django 3.0.3 on 2020-02-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=40)),
                ('gmail', models.CharField(max_length=60)),
                ('qualification', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=40)),
                ('gmail', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=200)),
                ('street2', models.CharField(max_length=200)),
                ('zip', models.IntegerField(max_length=5)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('id_proof', models.CharField(max_length=200)),
                ('proof_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.State')),
            ],
        ),
    ]
