# Generated by Django 3.0.3 on 2020-02-06 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visitor.Visitor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='check_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='check_out',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
