# Generated by Django 3.0.3 on 2020-02-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20200206_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.Country'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.State'),
        ),
    ]
